### ISSUE TITLE
ThreadLocal should be Send and Sync regardless of whether T is.

### ISSUE THREAD

**Issue by dylanede** [sfackler/thread-local-object#1]
At the moment, due to the use of `PhantomData<T>`, `ThreadLocal<T>` is only `Send` and `Sync` if `T` is, which partially defeats the point of the library. These bounds aren't required are they? The thread-local crate only requires `Send`, due to dropping potentially occurring on other threads, and since the dropping constraint does not exist in this crate, even the `Send` bound should not be necessary.

**Comment by sfackler** [comment]
I believe you're correct - we can add explicit impls of those traits.
