### ISSUE TITLE
Why is T required to be 'static?

### ISSUE THREAD

**Issue by fralalonde** [sfackler/thread-local-object#3]
I would like to set() dynamically created objects to the TL instance, the 'static bound seems to severely limit it's usefulness.

**Comment by sfackler** [comment]
What kind of thing do you want to store that isn't `'static`?

**Comment by fralalonde** [comment]
Nevermind, I am still confused about lifetimes. I've peppered _'statics_ around my code to satisfy the compiler and things now work perfectly. It's a shame this crate is ranked after `thread_local` on crates.io, because this one is much closer to what I expect a regular thread local to be.

I have a patch I could submit that recycles identifiers using a free list, which could help in some situations (32 bit, etc.) - it could be hidden behind a feature flag for those who need it. I wouldnt enable it by default because the free list Vec is unbound (for now) and the 64 bit method is so much simpler. Let me know if this interests you.

Also, have you considered taking in a default value generator on build? Something of the form ThreadLocal::with_default(F) where F: FnOnce() -> T would centralize the code for value initialization and make sure the app code never meets a `VacantEntry` for those cases where a default value makes sense.
